<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-20 00:20
=======
# Generated by Django 4.1.2 on 2022-10-19 23:35
>>>>>>> 790323f1bb8ae9cf4fb1f3402e6d28fb89fcc2ea

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('support_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_data', '0001_initial'),
>>>>>>> 790323f1bb8ae9cf4fb1f3402e6d28fb89fcc2ea
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
