<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-19 12:26
=======
# Generated by Django 4.1.2 on 2022-10-19 12:11
>>>>>>> 7c5ef61cc62e197f18d6e8775bbb536c4b880c20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
