# Generated by Django 4.1.2 on 2022-10-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='objection',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
