# Generated by Django 4.1.2 on 2022-10-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0003_support_objection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='objection',
            field=models.BooleanField(default=False),
        ),
    ]
